// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8htuQAMoLKbDavrqu-HPtpq7teu9oU-Q',
    appId: '1:759614451860:web:d132258b6166b0fd5a8481',
    messagingSenderId: '759614451860',
    projectId: 'listatareasfirebase-8fd3b',
    authDomain: 'listatareasfirebase-8fd3b.firebaseapp.com',
    storageBucket: 'listatareasfirebase-8fd3b.firebasestorage.app',
    measurementId: 'G-9NM8BDYQ7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk7IhEdZ_yzzisclWuQoBW319vm0CONAI',
    appId: '1:759614451860:android:dd556f380289ed045a8481',
    messagingSenderId: '759614451860',
    projectId: 'listatareasfirebase-8fd3b',
    storageBucket: 'listatareasfirebase-8fd3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKzQMNs49gBcJC17lH8lvVbtSwntcS-Vo',
    appId: '1:759614451860:ios:f260c6ce950824e75a8481',
    messagingSenderId: '759614451860',
    projectId: 'listatareasfirebase-8fd3b',
    storageBucket: 'listatareasfirebase-8fd3b.firebasestorage.app',
    iosBundleId: 'com.example.contactos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKzQMNs49gBcJC17lH8lvVbtSwntcS-Vo',
    appId: '1:759614451860:ios:f260c6ce950824e75a8481',
    messagingSenderId: '759614451860',
    projectId: 'listatareasfirebase-8fd3b',
    storageBucket: 'listatareasfirebase-8fd3b.firebasestorage.app',
    iosBundleId: 'com.example.contactos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8htuQAMoLKbDavrqu-HPtpq7teu9oU-Q',
    appId: '1:759614451860:web:424c55962d909a4b5a8481',
    messagingSenderId: '759614451860',
    projectId: 'listatareasfirebase-8fd3b',
    authDomain: 'listatareasfirebase-8fd3b.firebaseapp.com',
    storageBucket: 'listatareasfirebase-8fd3b.firebasestorage.app',
    measurementId: 'G-RCPGQBQNJ8',
  );
}
